### ISSUE TITLE
Send git commit id in build success emails

### ISSUE THREAD

**Issue by containscafeine** [CentOS/container-index#115]
$subject would really help for indexing purposes, since there are times when builds are auto trigerred, or when multiple commits are pushed, when I would like to know that the email is for which commit id in my tracked repository

**Comment by dharmit** [comment]
@containscafeine Thanks for bringing this up! Apologies for replying so late. I can see that having a commit ID would be handy when reading success/failure emails for the builds.

@bamachrn I think this is more suitable to be worked upon as a part of Pipeline Service. 

Since the Jenkins instance we use on ci.centos.org has Git plugin installed, this should be a matter of accessing the `GIT_COMMIT` environment variable and formatting the email to contain this information.

**Comment by bamachrn** [comment]
We are sending git commit ID and branch as cause of build, when the image is built due to change in the source repo. Closing this.
