### ISSUE TITLE
README doesn't talk about app-id parameter in index.d yml files

### ISSUE THREAD

**Issue by dharmit** [CentOS/container-index#38]
Is it just me or there's really no mention of `app-id` parameter we need in yml files under `index.d` directory to decide the namespace we would like to put a container image under? Maybe it got accidentally removed?

ping @mohammedzee1000 @kbsingh

**Comment by kbsingh** [comment]
the aim is to move towards deprecating it, with the filename mapping to the app-id as a default. since we had it already, the decision was to retain it in the existing configs so we can focus on the index split, instead of refactor code around it as well at the same time. once we have the index.d formats stable and consumeable, we will start working on enhacing the experience ( and include the removal of app-id )

**Comment by mohammedzee1000** [comment]
For now i have updated the readme to reflect the current need for app-id. So think this issue can be closed.

ping : @kbsingh @dharmit what do you think?

**Comment by dharmit** [comment]
@mohammedzee1000 sure, fine by me.
